### ISSUE TITLE
Privet

### ISSUE THREAD

**Issue by npearson72** [gongled/cartomatic#1]
Great script! I'm wondering, why would you include apache and nginx? Is nginx the default web server?

Also, it would be great if things like phpMyAdmin were optional. They're not great for security you know?

**Comment by gongled** [comment]
Hello, 
Thank you. I'm happy to hear that. 

I prefer installing NGINX as frontend server (just for static content like styles, images, scripts etc.) and Apache as application server on backend. I will remove phpMyAdmin with a big pleasure. I totally agree with you: it's not safe for production environment.

**Comment by gongled** [comment]
Done. https://github.com/gongled/cartomatic/commit/51e177d1c12f6dfb3369f321c9689bf8ebab6e74
