### ISSUE TITLE
Some security suggestions

### ISSUE THREAD

**Issue by npearson72** [gongled/cartomatic#2]
Is it possible for the script to block root user, and create a deploy user? Root user is the first to get attacked.

Also, I am noticing the script leaves seed and config files with the DB password in root user's home dir. Is it needed? It would be nice if the DB password was not shown and required manual entry instead of using .my.cnf

And finally, while not a security issue, I'm wondering if you can create an option to provision a Vagrant box for local development. I would be willing to help if you like?

Thanks and once again, great script! I love ansible and this script made provisioning a cs-cart server very easy.

**Comment by gongled** [comment]
> Is it possible for the script to block root user, and create a deploy user?

Of course it is possible. But I don't sure that it is expected action. In some cases, users have access to the server only via 'root'. If you forget to copy the new password then access to the server will be lost.

> Also, I am noticing the script leaves seed and config files with the DB password in root user's home dir. Is it needed?

It is required for database provisioning. But I can remove a configuration after all tasks.

> I'm wondering if you can create an option to provision a Vagrant box for local development.

I'm already have a Virtualbox environment for testing purposes. If you want I'm ready to publish a code to another repository. 

> Thanks and once again, great script! I love ansible and this script made provisioning a cs-cart server very easy.

Thank you!

**Comment by gongled** [comment]
Done. https://github.com/gongled/cartomatic-environment
