### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by haongz** [gongled/cartomatic#3]
Dear team,

The script cartomatic cannot support SSL. With automatic or manual install are not working? Please fix this issue.

Thanks!

**Comment by haongz** [comment]
Hi there,

hmm...

**Comment by Rafass** [comment]
It seems the issue can be fixed manually editing /etc/nginx/sites-enabled/<your_vhost>.conf and setup SSL manually. but I don't know exactly what lines.

**Comment by gongled** [comment]
Hi, there. I'm going to implement SSL/TLS on NGINX via Let's Encrypt service. Actually it helps to install certificate automatically and absolutely free. Unfortunately, I don't know what of ACME-client would be good to solve this problem.

**Comment by haongz** [comment]
I dont know setting SSL with nginx or apache :(

Try the tutorial https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority
many time but not ok :(

can you tell me how to setup SSL after install cartomatic with Digital Ocean???

**Comment by gongled** [comment]
You should edit NGINX configurations. First of all, you should edit /etc/nginx/sites-enabled/yourproject.conf, copy-paste 'server' block and do following things:
- Replace port 80 by 443.
- Uncomment lines which starts with 'ssl' and setup right path to the certificate and private key
- Uncomment line which starts with 'include xtra/proxy_params_ssl.conf' and remove 'include xtra/proxy_params.conf'
- Restart NGINX

That's all. I hope this instruction helps you to setup SSL manually.

**Comment by gongled** [comment]
Anyway, I'm going to do following plans:
- Support Debian-like systems (Ubuntu/Debian) will be canceled. All new features will be implemented for CentOS 6 and CentOS 7. That's will help me to focus all of my power on improvements. I can do it faster and qualitatively without any compatibilities with other distributions.
- All dependencies would be stored on my repository. I'm going to compile Apache, PHP, MySQL and other software for CS-Cart environment. 
- SSL support will be out-of-box. I'm going to use Let's Encrypt service via 'lego'.
- Varnish support will be implemented on this month after that CS-Cart 4.3.6 will be released.
- PHP 7.0 will be added.

**Comment by gongled** [comment]
Done. I'm going to merge this feature into master branch in the next release. https://github.com/gongled/cartomatic/commit/966ec2dcf614a7650b73c4fca4784ae22c7585aa
